---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: mavenwebappdeployment
spec:
 replicas: 2
 strategy: 
    type: Recreate
 selector: 
   matchLabels: 
     app: mavenwebapp
 template:
  metadata:
   name: mavenwebapppod
   labels:
     app: mavenwebapp	 
  spec: 
    containers:
    - name: mavenwebappcontainer
      image: vikas4uhere/maven-web-app-k8s
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
      resources:
       requests: 
        cpu: "0.5" 
         memory: "700Mi"
      
---
apiVersion: v1
kind: Service
metadata:
 name: mavenwebappsvc
spec:
  type: NodePort
  selector:
   app: mavenwebapp
  ports:
   - port: 80
     targetPort: 8080
     nodePort: 30689
...
